services:
  minimal-ros1-sim:
    image: ghcr.io/open-rmf/free_fleet/minimal-ros1-sim:noetic-latest
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true

  minimal-nav1-bringup:
    image: ghcr.io/open-rmf/free_fleet/minimal-nav1-bringup:noetic-latest
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true

  minimal-zenoh-bridge-ros1:
    image: ghcr.io/open-rmf/free_fleet/minimal-zenoh-bridge-ros1:noetic-latest
    network_mode: host
    stdin_open: true
    tty: true

  minimal-zenoh-router:
    image: eclipse/zenoh:${ZENOH_VERSION}
    restart: unless-stopped
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - RUST_LOG=debug
