services:
  minimal-nav2-bringup:
    image: ghcr.io/open-rmf/free_fleet/minimal-nav2-bringup:${ROS_DISTRO}-latest
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=42

  minimal-zenoh-bridge-ros2dds:
    image: ghcr.io/open-rmf/free_fleet/minimal-zenoh-bridge-ros2dds:${ROS_DISTRO}-latest
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - ROS_DOMAIN_ID=42

  minimal-zenoh-router:
    image: eclipse/zenoh:${ZENOH_VERSION}
    restart: unless-stopped
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - RUST_LOG=debug
