name: pull_request_ci
on: pull_request
jobs:

  ros1:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:melodic-ros-base-bionic
    steps:
    - name: deps
      run: |
        sudo apt update
        sudo apt install python-catkin-tools ros-melodic-move-base-msgs -y
        sudo apt install ros-melodic-tf2 ros-melodic-tf2-ros ros-melodic-tf2-geometry-msgs -y
        sudo apt install ros-melodic-actionlib ros-melodic-sensor-msgs -y
        mkdir -p /home/repos
        cd /home/repos/
        git clone https://github.com/osrf/free_fleet
    - name: checkout
      run: |
        cd /home/repos/free_fleet
        git checkout ${GITHUB_REF##*/}
    - name: merge
      run: |
        cd /home/repos/free_fleet
        git fetch
        git merge master
    - name: workspace
      run: |
        mkdir -p /home/ff_ws/src
        cd /home/ff_ws/src
        ln -s /home/repos/free_fleet/clients/ros1 free_fleet_client
    - name: build
      shell: bash
      run: |
        cd /home/ff_ws
        source /opt/ros/melodic/setup.bash
        catkin build free_fleet_client

  ros2:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
    steps:
    - name: deps
      run: |
        sudo apt update
        sudo apt install ros-eloquent-rmw-cyclonedds-cpp -y
        cd /home/
        mkdir repos
        cd repos/
        git clone https://github.com/osrf/free_fleet
        git clone https://github.com/osrf/rmf_core
    - name: checkout
      run: |
        cd /home/repos/free_fleet 
        git checkout ${GITHUB_REF##*/}
    - name: merge
      run: |
        cd /home/repos/free_fleet
        git fetch
        git merge master
    - name: workspace
      run: |
        cd /home/
        mkdir -p ff_ws/src
        cd ff_ws/src
        ln -s /home/repos/free_fleet/servers/ros2 free_fleet_server
        ln -s /home/repos/rmf_core rmf_core
    - name: build
      shell: bash
      run: |
        cd /home/ff_ws
        source /opt/ros/eloquent/setup.bash
        colcon build --packages-up-to free_fleet_server
