name: style
on: [push, pull_request]
jobs:
  style:
    runs-on: ubuntu-20.04
    container:
      image: docker://ros:foxy-ros-base-bionic

    steps:
    - uses: actions/checkout@v1

    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install pycodestyle wget

    - name: pycodestyle
      run: |
        pycodestyle .

    - name: rmf_uncrustify
      shell: bash
      run: |
        wget https://raw.githubusercontent.com/open-rmf/rmf_utils/main/rmf_utils/test/format/rmf_code_style.cfg
        source /opt/ros/foxy/setup.bash
        ament_uncrustify -c rmf_code_style.cfg .
